title: "Название твоего блога"
author: "Твое Имя"
description: "Краткое описание блога для поисковых систем"
baseurl: ""
url: "https://www.ogir.org"

# Настройки темы
remote_theme: emoleon/tale # Используем удаленную тему, чтобы не копировать лишний код
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Настройки пагинации (сколько постов на странице)
paginate: 5
paginate_path: "/page:num/"