title: "Ogir Blog"
tagline: "Заметки на полях"
description: "Блог на ogir.org"
url: "https://www.ogir.org"
baseurl: ""

# Используем стабильную тему от создателя Bootstrap
remote_theme: poole/lanyon

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5